# Generated by Django 4.2.1 on 2023-06-04 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media/sayt/news')),
                ('title_uz', models.CharField(max_length=512, verbose_name='Sarlavha')),
                ('title_ru', models.CharField(max_length=512, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=512, null=True, verbose_name='Title')),
                ('shortdesc_uz', models.TextField(null=True, verbose_name='Yangilikning Qisqa matni')),
                ('shortdesc_ru', models.TextField(null=True, verbose_name='Краткий текст сознания')),
                ('shortdesc_en', models.TextField(null=True, verbose_name='Short description')),
                ('desc_uz', models.TextField(null=True, verbose_name="Yangilikning To'liq matni")),
                ('desc_ru', models.TextField(null=True, verbose_name='Полный текст новости')),
                ('desc_en', models.TextField(null=True, verbose_name='Full text of the news')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='instagramm',
            new_name='instagram',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='odnoklassniki',
            new_name='ok',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='name',
        ),
        migrations.AddField(
            model_name='doctor',
            name='FIO',
            field=models.CharField(default=1, max_length=128, verbose_name='FIO'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='img',
            field=models.ImageField(upload_to='media/sayt/doc', verbose_name="Shifokor sur'ati"),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='motto',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Shifokor shiori'),
        ),
    ]
