# Generated by Django 4.2.2 on 2023-06-12 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_doctor_img_alter_new_date_alter_new_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('img', models.ImageField(blank=True, null=True, upload_to='diagnoz')),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=128, verbose_name='FIO')),
                ('birth', models.IntegerField(verbose_name="Tug'ulgan yili")),
            ],
        ),
        migrations.CreateModel(
            name='Tablets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nomi')),
                ('type', models.CharField(choices=[('Tomchi', 'Tomchi'), ('Tabletka', 'Tabletka'), ('Sirop', 'Sirop')], max_length=50, verbose_name='Turi')),
            ],
        ),
        migrations.AlterField(
            model_name='new',
            name='img',
            field=models.ImageField(upload_to='sayt/news', verbose_name='Yangilikning Rasmi'),
        ),
        migrations.CreateModel(
            name='Suggests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnoz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.diagnoz')),
            ],
        ),
        migrations.AddField(
            model_name='diagnoz',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.patients'),
        ),
    ]
