# Generated by Django 4.2.2 on 2023-06-12 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_diagnoz_patients_tablets_alter_new_img_suggests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggests',
            name='suggest',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='suggests',
            name='tablet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.tablets'),
        ),
        migrations.AlterField(
            model_name='tablets',
            name='type',
            field=models.CharField(choices=[('Tomchi', 'Tomchi'), ('Tabletka', 'Tabletka'), ('Sirop', 'Sirop')], default='Tabletka', max_length=50, verbose_name='Turi'),
        ),
    ]
