# Generated by Django 4.2.2 on 2023-06-12 15:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_suggests_suggest_suggests_tablet_alter_tablets_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnoz',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
