# Generated by Django 4.2.2 on 2023-06-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_diagnoz_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnoz',
            name='img',
        ),
        migrations.AlterField(
            model_name='suggests',
            name='suggest',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Maslahat'),
        ),
        migrations.AlterField(
            model_name='suggests',
            name='tablet',
            field=models.CharField(default=1, max_length=256, verbose_name='Dorining Nomi'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Tablets',
        ),
    ]
