# Generated by Django 4.2.2 on 2023-06-26 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_diagnoz_img_alter_suggests_suggest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tablets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Nomi')),
                ('type', models.CharField(choices=[('Tomchi', 'Tomchi'), ('Tabletka', 'Tabletka'), ('Sirop', 'Sirop')], default='Tabletka', max_length=50, verbose_name='Turi')),
            ],
        ),
        migrations.AlterField(
            model_name='suggests',
            name='tablet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.tablets'),
        ),
    ]
